// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/mls-explorer': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mls-explorer.get').default>>>>
    }
    '/api/mls-properties': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mls-properties.get').default>>>>
    }
    '/api/mls-score': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mls-score').default>>>>
    }
    '/api/mls-scoring-analysis': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mls-scoring-analysis.get').default>>>>
    }
    '/api/properties': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties.get').default>>>>
    }
    '/api/upload-csv': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload-csv.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}